name: Hello Github Actions
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from Github actions!"
      - run: echo "i'll list files"
      - run: ls -al
      
